#!/bin/bash

set -euo pipefail

if [[ "${1:-}" == "--rocm" ]]; then
    docker build -t manylinux-rocm -f docker/rocm-on-manylinux.Dockerfile .
    docker run --rm -v $(pwd):/project -w /project manylinux-rocm \
        AIMDO_EXTRA_CFLAGS=-Werror bash ./scripts/build-linux-aimdo.sh --rocm
else
    docker build -t manylinux-cuda -f docker/cuda-on-manylinux.Dockerfile .
    docker run --rm -v $(pwd):/project -w /project manylinux-cuda \
        AIMDO_EXTRA_CFLAGS=-Werror bash ./scripts/build-linux-aimdo.sh
fi
